"""Add date_created field to Tournament

Revision ID: 2b73b8cdde2d
Revises: d58fae2290e4
Create Date: 2025-06-03 10:59:51.847035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b73b8cdde2d'
down_revision = 'd58fae2290e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
