"""add creator_id with FK name

Revision ID: 8d34a847db61
Revises: a9ffa4873be9
Create Date: 2025-06-02 19:24:28.222473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d34a847db61'
down_revision = 'a9ffa4873be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tournament_creator', 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournament_creator', type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
