"""Recreate cascade deletes

Revision ID: 98af804a6392
Revises: 2b73b8cdde2d
Create Date: 2025-06-03 13:57:06.934398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98af804a6392'
down_revision = '2b73b8cdde2d'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_discussion_author', 'user', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('discussion_message', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_msg_discussion', 'discussion', ['discussion_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_msg_author', 'user', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_goal_player', 'player', ['player_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_goal_team', 'team', ['team_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_goal_match', 'match', ['match_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lineup', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_lineup_player', 'player', ['player_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_lineup_team', 'team', ['team_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_lineup_match', 'match', ['match_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_match_team2', 'team', ['team2_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_match_team1', 'team', ['team1_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_match_tournament', 'tournament', ['tournament_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_player_team', 'team', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_team_tournament', 'tournament', ['tournament_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tournament_creator'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tournament_creator', 'user', ['creator_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournament_creator', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tournament_creator'), 'user', ['creator_id'], ['id'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_tournament', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tournament', ['tournament_id'], ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('fk_player_team', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint('fk_match_tournament', type_='foreignkey')
        batch_op.drop_constraint('fk_match_team1', type_='foreignkey')
        batch_op.drop_constraint('fk_match_team2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['team1_id'], ['id'])
        batch_op.create_foreign_key(None, 'tournament', ['tournament_id'], ['id'])
        batch_op.create_foreign_key(None, 'team', ['team2_id'], ['id'])

    with op.batch_alter_table('lineup', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lineup_match', type_='foreignkey')
        batch_op.drop_constraint('fk_lineup_team', type_='foreignkey')
        batch_op.drop_constraint('fk_lineup_player', type_='foreignkey')
        batch_op.create_foreign_key(None, 'match', ['match_id'], ['id'])
        batch_op.create_foreign_key(None, 'player', ['player_id'], ['id'])
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_goal_match', type_='foreignkey')
        batch_op.drop_constraint('fk_goal_team', type_='foreignkey')
        batch_op.drop_constraint('fk_goal_player', type_='foreignkey')
        batch_op.create_foreign_key(None, 'player', ['player_id'], ['id'])
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])
        batch_op.create_foreign_key(None, 'match', ['match_id'], ['id'])

    with op.batch_alter_table('discussion_message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_msg_author', type_='foreignkey')
        batch_op.drop_constraint('fk_msg_discussion', type_='foreignkey')
        batch_op.create_foreign_key(None, 'discussion', ['discussion_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discussion_author', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###
